apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin #YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: password123 #cGFzc3dvcmQxMjM=
# data:

