apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque
stringData:
  MONGODB_USER: admin #YWRtaW4=
  MONGODB_PASSWORD: password123 #cGFzc3dvcmQxMjM=
